Flashcards/Flashcards/Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Services.Interfaces;
using System.Web.Mvc;
using Flashcards.Code;
using Flashcards.Entities;

namespace Flashcards.Controllers
{
    public class LanguageController : ControllerBase
    {
        private readonly IFlashcardUnit unit;
        public LanguageController(IPopupService popupService, ISessionService sessionService, IFlashcardUnit unit) : base(popupService, sessionService)
        {
            this.unit = unit;
        }
        [Authorize(Roles = Groups.User)]
        [HttpPost]
        public ActionResult ChangeLanguage(int currentLanguageID)
        {
            var language = unit.LanguageRepository.GetById(currentLanguageID);

            if (language == null)
                return RedirectBackWithError("Language does not exist!");

            sessionService.LanguageID = language.ID;
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }
    }
}

Flashcards/Flashcards/Views/Shared/_Layout.cshtml
@using Services.Models;
@using Services.Enums;
@using Flashcards.Code;
@{
    var messages = TempData["Messages"];
    List<PopupMessageViewModel> messageList = null;
    if (messages != null)
    {
        messageList = messages as List<PopupMessageViewModel>;
    }
    else
    {
        messageList = new List<PopupMessageViewModel>();
    }

    var langs = Globals.GenerateLanguageSelectList();

    var session = DependencyResolver.Current.GetService<Services.Interfaces.ISessionService>();
    var userInfo = session.UserInfo;
    var training = userInfo?.TrainingInfo;
    var review = userInfo?.ReviewInfo;
}



<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                @Html.ActionLink("Flashcards", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (session.UserID != null)
                    {
                        <li>@Html.ActionLink("Training", "Training", "Training")</li>
                        <li>@Html.ActionLink("Review", "Review", "Review")</li>
                    }
                    @if (session.UserInfo != null && session.UserInfo.Username == "admin")
                    {
                        <li>@Html.ActionLink("Management", "Index", "Management")</li>
                    }
                    <li style="height:50px">
                        <div style="display:flex; align-items:center; align-content:center; justify-content:center; height:100%">
                            @using (Html.BeginForm("ChangeLanguage", "Language", FormMethod.Post, new { id = "languageChangeForm" }))
                            {
                                @Html.DropDownList("currentLanguageID", langs)
                            }
                        </div>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="warningMessages">
        @foreach (var message in messageList)
        {
            <div class="popupMessage @message.MessageType.GetMessageClass()">
                <div class="close"><i class="fa fa-close"></i></div>
                <div class="message">
                    @Html.Raw(message.Content)
                </div>
            </div>
        }
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            <p>@(userInfo?.Username) - @(userInfo?.UserID) - @session.LanguageID</p>

            @if (review != null)
            {
                <p>Review Info</p>
                <div>
                    ID - @review.ReviewID, languageID - @review.LanguageID, Date Started - @review.DateStarted.ToShortDateString()
                    <ul>
                        @foreach (var card in review.ReviewCards)
                        {
                            <li>
                                @card.FlashcardID - @card.InternalLossCount
                            </li>
                        }
                    </ul>
                </div>
            }

            @if (training != null)
            {
                <p>Training Info</p>
                <div>
                    ID - @training.TrainingID, Date Started - @training.DateStarted.ToShortDateString()
                    <ul>
                        @foreach (var card in training.Cards)
                        {
                            <li>
                                @card.FlashcardID - @card.InternalLossCount - @card.LanguageID
                            </li>
                        }
                    </ul>
                </div>
            }
        </footer>
    </div>
    @Scripts.Render("~/bundles/scalaDependencies")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/core")
    @Scripts.Render("~/bundles/scala")
    @RenderSection("scripts", required: false)
    <script type="text/javascript">
        InitFlashcard("@ViewBag.Module");
    </script>
</body>
</html>